### PR TITLE
Add setValue() function to allow you to change slider value programatically

### PR DESCRIPTION
**Pull request by marcshilling**
I'm using the slider as a video player scrubber, so I needed to increment the slider's value in code every second. This function allows me to do so. I added `this.state.sliding` so that calls to `setValue()` while the user is dragging the thumb are ignored. I also go ahead and set the slider to the `maximumValue` if the value passed to `setValue()` is within 1 or greater than the `maximumValue`.

### CODE REVIEW

**Comment by marcshilling** [comment]
FYI - looks like my editor stripped a bunch of trailing whitespace chars, that's why the diff looks so busy.

**Comment by jeanregisser** [comment]
Hi,

It looks like you can accomplish what you did without modifying the current code of the slider.
You can update the `value` prop passed to the slider and base it on your own custom state logic.
To prevent changing the thumb position while the user is dragging it, you can use a bool `sliding` variable set to true when `onValueChange` is called and set to false when `onSlidingComplete` is called.
Then when your timer fires to update the value, you don't anything if `sliding == true`.

**Comment by jeanregisser** [comment]
I see however that's there's a bug in the current implementation, preventing an updated `value` prop from actually updating the position.
I'm pushing a fix for this soon.

**Comment by marcshilling** [comment]
@jeanregisser thanks - with your latest version it works by updating the value prop.

One minor suggestion though...can you either add an `onSlidingStart` callback prop OR send an initial `onValueChange` immediately upon touching down on the thumb? By using your method of setting a `sliding` bool to true in onValueChange, it doesn't reflect that the user has interacted with the slider until they actually move the touch. I would expect that as soon as I touch down on the thumb, my timer events stop firing because I am technically interacting.

**Comment by jeanregisser** [comment]
Indeed!
The new 0.2.0 version now has a `onSlidingStart` callback prop.

Thanks @marcshilling

**Comment by marcshilling** [comment]
Awesome, thanks @jeanregisser...the slider perfectly suits my needs now!

**Pull request closed without merging**
