### PR TITLE
Fix RTL language support

### PR DESCRIPTION
**Pull request by lyahdav**

### CODE REVIEW

**Comment by yoavkamary** [comment]
@lyahdav Thanks you for the PR.
I tested and now the touch area of the thumb is positioned well on RTL but when moving the slider the thumb itself is rendered out of position. 
Can you update your PR with this change:

On Slider.js replace line 238
 ```outputRange: [0, containerSize.width - thumbSize.width]```
with: 
 ```outputRange: I18nManager.isRTL ? [0, -(containerSize.width - thumbSize.width)] : [0, containerSize.width - thumbSize.width]```

Thanks
Yoav

**Comment by lyahdav** [comment]
@yoavkamary can you send a screenshot of the rendering out of position? I didn't see that in my testing.

**Comment by bitcrumb** [comment]
I've opened a new PR that fixed all RTL issues: #119

**Comment by jeanregisser** [comment]
Thanks! Closing this now that #119 has been merged.

**Pull request closed without merging**
