### PR TITLE
addDisabled

### PR DESCRIPTION
**Pull request by manask88**
add property to disable the slider

### CODE REVIEW

**Comment by jaywalklabs** [comment]
+1 on this, is there anything preventing this PR to be merged?

**Comment by jhen0409** [comment]
+1
@jeanregisser ping

**Comment by gwhite-dayspring** [comment]
+1
@jeanregisser ping again

**Comment by jeanregisser** [comment]
Looks good thanks @manask88!
Sorry for the rather long delay here :smile_cat:

**Comment by gwhite-dayspring** [comment]
@jeanregisser hakuna matata my friend. Thanks for taking the time!

**Pull request merged**
