### PR TITLE
Adding text in slider thumb

### PR DESCRIPTION
**Pull request by gianpieroc**
Hello! Great project!... I had to modify this library adding texts in slider thumb... So why not a PR with this feature? The user can specify a text for the thumb with a prop called thumbText and style it with thumbStyleText.

I updated the example, but I don't know if include this here..

### CODE REVIEW

**Comment by JeremyBradshaw7** [comment]
Would welcome this feature

**Review by nikolaigeorgie — APPROVED** [review]

**Comment by nikolaigeorgie** [comment]
ready to merge.

**Comment by nikolaigeorgie** [comment]
👍 lets do this

**Comment by gianpieroc** [comment]
Did something happen?

**Pull request closed without merging**
