### PR TITLE
A bit more flexible package.json

### PR DESCRIPTION
**Pull request by jeveloper**
I think this covers minimum that everyone should have

### CODE REVIEW

**Comment by jeveloper** [comment]
is Anyone out there? @jeanregisser

**Comment by jeanregisser** [comment]
@jeveloper these are devDependencies, why do you want to update them?

**Comment by jeveloper** [comment]
Just contributing  a bit to the project :)

By the way, RN 37 removes SliderIOS (although i dont think you use it) in favour of Slider

**Comment by jeanregisser** [comment]
Thanks, I'm closing this as these are now outdated as well.

**Pull request closed without merging**
